// Source for the committed, self-hosted Lucide bundle. Run npm run build:icons.
import {
  createIcons,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Backpack,
  CalendarClock,
  ChevronRight,
  CloudOff,
  DoorClosed,
  Link,
  PartyPopper,
  Play,
  Shapes,
  SunMoon,
  Sun,
  Sprout,
  Utensils,
} from "lucide";
const icons = {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Backpack,
  CalendarClock,
  ChevronRight,
  CloudOff,
  DoorClosed,
  Link,
  PartyPopper,
  Play,
  Shapes,
  SunMoon,
  Sun,
  Sprout,
  Utensils,
};
window.lucide = {
  createIcons: (options) => createIcons({ ...options, icons }),
};
